//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection listRecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["listRecentProjects"]));
            }
            set {
                this["listRecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int applicationLanguage {
            get {
                return ((int)(this["applicationLanguage"]));
            }
            set {
                this["applicationLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color spikeBarColor {
            get {
                return ((global::System.Drawing.Color)(this["spikeBarColor"]));
            }
            set {
                this["spikeBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color spikeBarColorInput {
            get {
                return ((global::System.Drawing.Color)(this["spikeBarColorInput"]));
            }
            set {
                this["spikeBarColorInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color spikeBarColorLay1 {
            get {
                return ((global::System.Drawing.Color)(this["spikeBarColorLay1"]));
            }
            set {
                this["spikeBarColorLay1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color spikeBarColorOutput {
            get {
                return ((global::System.Drawing.Color)(this["spikeBarColorOutput"]));
            }
            set {
                this["spikeBarColorOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Networks\\")]
        public string pathStructures {
            get {
                return ((string)(this["pathStructures"]));
            }
            set {
                this["pathStructures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Stimulus\\")]
        public string pathStimuli {
            get {
                return ((string)(this["pathStimuli"]));
            }
            set {
                this["pathStimuli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Output\\")]
        public string pathOutput {
            get {
                return ((string)(this["pathOutput"]));
            }
            set {
                this["pathOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstLaunch {
            get {
                return ((bool)(this["firstLaunch"]));
            }
            set {
                this["firstLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int howManyRecent {
            get {
                return ((int)(this["howManyRecent"]));
            }
            set {
                this["howManyRecent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Hardware\\")]
        public string pathHardware {
            get {
                return ((string)(this["pathHardware"]));
            }
            set {
                this["pathHardware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool languageChange {
            get {
                return ((bool)(this["languageChange"]));
            }
            set {
                this["languageChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Hardware\\ANN\\src\\")]
        public string pathAnnSrc {
            get {
                return ((string)(this["pathAnnSrc"]));
            }
            set {
                this["pathAnnSrc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Hardware\\SNN\\src\\")]
        public string pathSnnSrc {
            get {
                return ((string)(this["pathSnnSrc"]));
            }
            set {
                this["pathSnnSrc"] = value;
            }
        }
    }
}
